import { useAtom } from "jotai";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Grid from "../components/Grid";
import Keyboard from "../components/Keyboard";
import {
  currentGuessAtom,
  currentGuessFullAtom,
  guessedWordsAtom,
  searchedWordAtom,
  modalAtom,
  isGuestAtom,
} from "../store/store";
import { WORDS } from "../lib/wordlist";
import Modal from "../components/Modal";

const Home: NextPage = () => {
  const [letter, setLetter] = useAtom(currentGuessAtom);
  const [guessWord] = useAtom(currentGuessFullAtom);
  const [, setGuessWordsArray] = useAtom(guessedWordsAtom);
  const [searchedWord] = useAtom(searchedWordAtom);
  const [, setIsModalOpen] = useAtom(modalAtom);
  const { data: sessionData } = useSession();
  const [isGuest] = useAtom(isGuestAtom);

  const allKeys = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

  const onEnter = () => {
    if (guessWord === searchedWord) {
      const word = guessWord;
      setLetter([]);
      setGuessWordsArray((prev) => {
        return [...prev, word];
      });
      setIsModalOpen(true);
    } else {
      if (letter.length < 5) {
        return;
      }

      if (WORDS.includes(guessWord.toLowerCase())) {
        const word = guessWord;
        setLetter([]);
        setGuessWordsArray((prev) => {
          return [...prev, word];
        });
      } else {
        alert("Invalid");
      }
    }
  };

  const onChar = (key: string) => {
    const wordLength = letter.length;

    if (key === "Backspace") {
      onBackspace();
    }

    if (key === "Enter") {
      onEnter();
      return;
    }

    if (wordLength < 5 && allKeys.includes(key.toUpperCase())) {
      setLetter((prev) => {
        if (prev.length < 5) return [...prev, key.toUpperCase()];

        return prev;
      });
      return;
    }
  };

  const onBackspace = () => {
    setLetter((prev) => prev.slice(0, letter.length - 1));
    return;
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      onChar(e.key);
    };

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [onEnter]);

  return (
    <>
      <Head>
        <title>Wordle clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex min-h-screen w-screen flex-col bg-black">
          {sessionData && (
            <div className="m-4 flex gap-2 self-end">
              <Image
                alt="Profile picture"
                className="mr-1 rounded-full object-cover"
                src={sessionData.user?.image ? sessionData.user.image : ""}
                width={48}
                height={48}
              />
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => signOut()}
              >
                Log out
              </button>
            </div>
          )}
          {(sessionData || isGuest) && (
            <Game onChar={onChar} onEnter={onEnter} onBackspace={onBackspace} />
          )}
          {!sessionData && !isGuest && <Login />}
        </div>
      </main>
    </>
  );
};

export default Home;

const Game = ({
  onChar,
  onEnter,
  onBackspace,
}: {
  onChar: (value: string) => void;
  onEnter: () => void;
  onBackspace: () => void;
}) => {
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-4">
      <Grid />
      <Keyboard onChar={onChar} onEnter={onEnter} onBackspace={onBackspace} />
      <Modal />
    </div>
  );
};

const Login: React.FC = () => {
  const [, setIsGuest] = useAtom(isGuestAtom);

  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-8">
      <h1 className="text-4xl text-white">Wordle</h1>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={() => signIn()}
      >
        Log in
      </button>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={() => setIsGuest(true)}
      >
        Play as guest
      </button>
    </div>
  );
};
